confs = \
        \
	ConsoleKit,trunk.lcopy \
	Kahua,trunk.lcopy \
	NetworkManager,trunk.lcopy \
	anaconda,trunk.lcopy \
	asakusafw,trunk.lcopy \
	attr,trunk.lcopy \
	audit,trunk.lcopy \
	autoconf,trunk.lcopy \
	autofs,trunk.lcopy \
	automake,trunk.lcopy \
	bind,released.lcopy \
	binutils,trunk.lcopy \
	biwascheme,trunk.lcopy \
	cairo,trunk.lcopy \
	cc-mode,trunk.lcopy \
	cluster,stable31.lcopy \
	cluster,trunk.lcopy \
	coreutils,trunk.lcopy \
	corosync,trunk.lcopy \
	ctags,trunk.lcopy \
	cups,trunk.lcopy \
	cygwin,trunk.lcopy \
	ddskk,trunk.lcopy \
	device-mapper-multipath,trunk.lcopy \
	dhcp,trunk.lcopy \
	dlm,trunk.lcopy \
	dovecot,2_1.lcopy \
	e2fsprogs,trunk.lcopy \
	eclipse-sequoyah,trunk.lcopy \
	emacs,trunk.lcopy \
	emacs-mew,trunk.lcopy \
	emacs-w3m,trunk.lcopy \
	ethtool,trunk.lcopy \
	fence,trunk.lcopy \
	fence-agents,trunk.lcopy \
	flashcache,trunk.lcopy \
	gauche,trunk.lcopy \
	gauche-mode,trunk.lcopy \
	gcc,trunk.lcopy \
	gdb,trunk.lcopy \
	gdm,trunk.lcopy \
	gentoo-x86,trunk.lcopy \
	gfs2-utils,trunk.lcopy \
	glib2,trunk.lcopy \
	glibc,ports.lcopy \
	glibc,trunk.lcopy \
	glucsterfs,trunk.lcopy \
	gnash,trunk.lcopy \
	gonzui,trunk.lcopy \
	goocanvas,trunk.lcopy \
	grub2,trunk.lcopy \
	gstreamer,trunk.lcopy \
	gtk2,trunk.lcopy \
	hachoir,trunk.lcopy \
	hal,trunk.lcopy \
	hieroglyph,trunk.lcopy \
	httpclient,trunk.lcopy \
	httpd,trunk.lcopy \
	ietf-draft,trunk.lcopy \
	initscripts,trunk.lcopy \
	iproute,trunk.lcopy \
	keepalived,trunk.lcopy \
	kernel,dlm.lcopy \
	kernel,kbuild.lcopy \
	kernel,kvm.lcopy \
	kernel,net-next.lcopy \
	kernel,rt.lcopy \
	kernel,trunk.lcopy \
	kernel,xen-3_2.lcopy \
	kexec-tools,trunk.lcopy \
	lcopy,trunk.lcopy \
	libbonobo,trunk.lcopy \
	libdwarves,trunk.lcopy \
	liboil,trunk.lcopy \
	libpcap,trunk.lcopy \
	libtool,trunk.lcopy \
	libvirt,trunk.lcopy \
	lm-sensors,trunk.lcopy \
	ltp,trunk.lcopy \
	lvm2,trunk.lcopy \
	m4,trunk.lcopy \
	make,trunk.lcopy \
	man-pages,trunk.lcopy \
	mdadm,trunk.lcopy \
	miniascape,trunk.lcopy \
	mock,trunk.lcopy \
	monotone,trunk.lcopy \
	net-snmp,trunk.lcopy \
	netbsd-kernel,trunk.lcopy \
	nfs-utils,trunk.lcopy \
	openais,trunk.lcopy \
	openid4java,trunk.lcopy \
	openldap,trunk.lcopy \
	openssh,trunk.lcopy \
	openssl,trunk.lcopy \
	ovirt-engine,trunk.lcopy \
	pam,trunk.lcopy \
	perg,trunk.lcopy \
	php,trunk.lcopy \
	portage,trunk.lcopy \
	postgresql,trunk.lcopy \
	prelcopy,trunk.lcopy \
	python-virtinst,trunk.lcopy \
	qemu,kvm.lcopy \
	qemu,trunk.lcopy \
	qt-jambi,trunk.lcopy \
	reactos,trunk.lcopy \
	resource-agents,trunk.lcopy \
	rgmanager,trunk.lcopy \
	rpm,rpm5.lcopy \
	rpm,trunk.lcopy \
	rsyslog,trunk.lcopy \
	samba,trunk.lcopy \
	sblim-cmpi-base,trunk.lcopy \
	sblim-cmpi-syslog,trunk.lcopy \
	sblim-sfcb,trunk.lcopy \
	sblim-wbemcli,trunk.lcopy \
	sbuild,trunk.lcopy \
	scheme2js,released.lcopy \
	scsi-target-utils,trunk.lcopy \
	shadow-utils,trunk.lcopy \
	sop,trunk.lcopy \
	sos,trunk.lcopy \
	source-highlight,trunk.lcopy \
	spacewalk,trunk.lcopy \
	spice,qxl.lcopy \
	spice,trunk.lcopy \
	spice,vdesktop.lcopy \
	spice,vdi_agent.lcopy \
	spice,vdi_port.lcopy \
	spice,vdi_slirp.lcopy \
	squid,trunk.lcopy \
	srpmix,trunk.lcopy \
	stitch,trunk.lcopy \
	strace,trunk.lcopy \
	sysstat,trunk.lcopy \
	systemd,trunk.lcopy \
	systemtap,trunk.lcopy \
	texinfo,trunk.lcopy \
	tog-pegasus,trunk.lcopy \
	twig,trunk.lcopy \
	udev,trunk.lcopy \
	uim,trunk.lcopy \
	unetstack,trunk.lcopy \
	util-linux,trunk.lcopy \
	util-linux-ng,trunk.lcopy \
	vim,trunk.lcopy \
	virt-manager,trunk.lcopy \
	virt-v2v,trunk.lcopy \
	wfo,trunk.lcopy \
	wireshark,trunk.lcopy \
	with-log,trunk.lcopy \
	xorg-x11-drv-mga,trunk.lcopy \
	xorg-x11-server,trunk.lcopy \
	xpad,trunk.lcopy \
	xtrace,trunk.lcopy \
	ymacs,trunk.lcopy \
	yogomacs,trunk.lcopy \
	yum,trunk.lcopy \
	yum-utils,trunk.lcopy \
	zsh,trunk.lcopy \
	\
	$(NULL)
