#!/bin/bash

BACKEND=svn
VERSION="0.0.0"

source liblcopy_backends.sh || exit 1

function write_spec
{
    local repo=$1

    common_write_spec 
    printf "SVN_REPOSITORY=\"%s\"\n" "${repo}"
}

function repo_check
{
    local repo=$1

    if [ -z "${repo}" ]; then
	echo "broken svn command line: cannot find repository specification" 1>&2
	return 1
    fi

    local http_spec="^http://.*$"
    local https_spec="^https://.*$"
    local svn_spec="^svn://.*$"
    if  ! ( [[ "$repo" =~ $http_spec ]]  || \
	    [[ "$repo" =~ $https_spec ]] || \
	    [[ "$repo" =~ $svn_spec ]] ); then
	echo "broken svn command line: unrecognizable repo specification: $repo" 1>&2
	echo "expected repo specifications: " 1>&2
	for s in "$http_spec" "$https_spec" "$svn_spec"; do
	    echo "	$s" 1>&2
	done
	return 1
    else
	return 0
    fi
}

#
# HELP
#
function svn_help_help
{
    common_help_help "$@"
}

function svn_help
{
    common_help "$@"
}

#
# GENCONF_FORMAT
# 
function svn_genconf_format
{
    common_genconf_format "$@"
}

#
# GENCONF
# 
function svn_help_genconf
{
    local prefix

    if [ "$1" != "format" ]; then
	prefix="$0 genconf"
    fi

    echo "	" ${prefix} svn 'checkout|co' URL
    echo "	" "(acceptable scheme for URL: http://..., https://..., and svn://...)"
}

function svn_genconf
{
    local original=$@
    local cmd
    local repo


    if [ $# != 2 ]; then
	echo "wrong number of arguments: $original" 1>&2
	return 1
    fi


    cmd=$1
    shift
    if ! ( [ "$cmd" = "co" ] || [ "$cmd" = "checkout" ] ); then
	echo "unknown command for checkout: $cmd" 1>&2
	return 1
    fi
    
    repo=$1
    shift
    if ! repo_check "${repo}"; then
	return 1
    fi
    write_spec "${repo}"
    return 0
}

#
# CHECKOUT
#
function svn_help_checkout
{
    echo "	$0 " "checkout" "FILE.lcopy" "OUTPUT-DIR"
}

function svn_checkout
{
    local input=$1
    local output_dir=$2

    if ! source "$input"; then
	return 1
    fi

    if [ -z "${SVN_REPOSITORY}" ]; then
	echo "no SVN_REPOSITORY in $input" 1>&2
	return 1
    fi

    ( 
	cd ${output_dir}

	common_spawn svn checkout "${SVN_REPOSITORY}"
    )

    return $?
}

#
# PRINT_CMDLINE
#
function svn_help_print_cmdline
{
    echo "	$0 " "print_cmdline" "FILE.lcopy" "checkout"
}

function svn_print_cmdline
{
    local input=$1
    local cmd=$2

    if ! source "$input"; then
	return 1
    fi

    if [ "$cmd" = "checkout" ]; then
	if [ -z "${SVN_REPOSITORY}" ]; then
	    echo "no SVN_REPOSITORY in $input" 1>&2
	    return 1
	fi
	echo svn checkout "${SVN_REPOSITORY}"
    else
	return 1
    fi

    return 0
}

#
# UPDATE
#
function svn_help_update
{
    echo "	$0 " "update" "FILE.lcopy" "UPDATE-DIR"
}

function svn_update
{
    local input=$1
    local update_dir=$2
    local log=/tmp/svn-update-$$


    cd "${update_dir}"

    if common_spawn svn update | tee $log; then
	if [ "$(wc -l < $log)" = 1 ] && \
	   LANG=C grep  'At revision' $log > /dev/null 2>&1; then
	    rm -f $log
	    return 0
	else
	    rm -f $log
	    return 1
	fi
    else
	rm -f $log
	return 2
    fi
}

#
# DIRP
# 
function svn_help_dirp
{
    echo "	$0 " "dirp" "[DIR]"
}

function svn_dirp
{
    local dir=${1:-$(pwd)}
    
    test -d ${dir}/.svn
}

#
# REBIRTH
#
function svn_help_rebirth
{
    echo "	$0 " "rebirth" "[DIR]"
}

function svn_rebirth
{
    local dir=${1:-$(pwd)}

    if ! svn_dirp ${dir}; then
	echo "Not svn directory: ${dir} " 1>&2
	return 1
    fi


    local svn_info=$(svn info)
    if [ $? != 0 ]; then
	echo "failed in svn info invocation (pwd: $(pwd))" 1>&2
	return 1
    fi

    local svn_url=$(echo "$svn_info" | grep 'URL: ' |  sed -e 's/URL: //')
    if [ -z "${svn_url}" ]; then
	echo "cannot find URL line in svn info output (pwd: $(pwd)) " 1>&2
	return 1
    fi

    local repo="${svn_url}"
    if ! repo_check "${repo}"; then
	return 1
    fi

    write_spec "${repo}"
}

function main
{
    common_main "$@"
    return $?
}

main "$@"
exit $?
